# Automatically generated by Updater v1.0
# @author Daniel J. Finnegan

import shutil, os, os.path, sys
from subprocess import call

project_root = os.getcwd()

sys.path.append(os.path.join(project_root, 'scripts'))
from builder import build_project

if __name__ == '__main__':
	shutil.rmtree('bin', ignore_errors=True)
	shutil.rmtree('build', ignore_errors=True)
	shutil.rmtree('src', ignore_errors=True)

	build_project.build_full_package(project_root)
